version: "3.7"

services:
  mongoDB:
    image: mongo:5.0.20
    container_name: ecom-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network
  backend:
    container_name: ecom-backend
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      target: Production
    ports:
      - 5000:5000
    networks:
      - shared-network
    depends_on:
      - mongoDB
    environment:
      - DB_URI=mongodb://localhost:27017/Ecommerce
      - PORT=5000
      - JWT_SECRETE=ITSMEHADESYOUBITCH
      - JWT_EXPIRE=5d
      - COOKIE_EXPIRE=5
      - EMAIL_SERVICE=gmail
      - EMAIL_USERNAME=hadees0963@gmail.com
      - EMAIL_PASSWORD=9Pra9Sad
      - CLOUDINARY_CLOUD_NAME=dqo3gfjis
      - CLOUDINARY_API_KEY=683841419184121
      - CLOUDINARY_API_SECRET=XOMl1XH0raYS_HOXrSft-pZrFc8
      - STRIPE_API_KEY=pk_test_51NS0ZVSJCg32PsaeKZk0gwQvewPITnuIsZitdRk07rBS6r1NWW4RMHECb5kvyLjSeUJygi0g6bf7ng6cJUEnBDEn00DCifU4vp
      - STRIPE_SECRET_KEY=sk_test_51NS0ZVSJCg32PsaeRPf34qhiKAP2tmQjSTOjCl14yuHd0XknSIl6dGbIj5Jd7JunnPRjfFWxzVwEDAMIJkkXE0Kp00pAyF3RgO


  frontend:
    container_name: ecom-frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
      target: Production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - shared-network
    tty: true
    stdin_open: true
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000

networks:
  shared-network:
  mongo-network:
