export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILS = "PRODUCT_LIST_FAILS";
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILS = "PRODUCT_DETAILS_FAILS";

export const   CLEAR_ERRORS = "CLEAR_ERRORS";


export const ADD_NEW_REVIEW_REQUEST = "ADD_NEW_REVIEW_REQUEST";
export const ADD_NEW_REVIEW_SUCCESS = "ADD_NEW_REVIEW_SUCCESS";
export const ADD_NEW_REVIEW_FAILS = "ADD_NEW_REVIEW_FAILS";
export const ADD_NEW_REVIEW_RESET = "ADD_NEW_REVIEW_RESET";


export const ADMIN_PRODUCT_LIST_REQUEST = "ADMIN_PRODUCT_LIST_REQUEST";
export const ADMIN_PRODUCT_LIST_SUCCESS = "ADMIN_PRODUCT_LIST_SUCCESS";
export const ADMIN_PRODUCT_LIST_FAILS = "ADMIN_PRODUCT_LIST_FAILS";
export const ADMIN_PRODUCT_DETAILS_REQUEST = "ADMIN_PRODUCT_DETAILS_REQUEST";
